- id: verify
  name: verify
  entry: dbt2looker --prefilter --strict --dry-run -ts DATABASE -s
  description: "verify that dbt models are compatible with Looker"
  language: python
  require_serial: false
  types_or: [sql]

- id: generate
  name: generate
  entry: dbt2looker --prefilter -ts DATABASE -s
  description: "generate Looker model files from catalog and manifest for modified models"
  language: python
  require_serial: true
  types_or: [sql]
