repos:
  # - repo: https://github.com/akaihola/darker
  #   rev: 1.3.2
  #   hooks:
  #     - id: darker #lints python code like Black but only for
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
      - id: ruff-format

  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v1.2.3
  #   hooks:
  #     - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: trailing-whitespace # trims trailing whitespace.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: detect-private-key # detects the presence of private keys.

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["--exclude", "test", "--skip", "B608"]

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v4.0.0-alpha.8
  #   hooks:
  #     - id: prettier
  #       files: \.(js|ts|jsx|tsx|css|less|html|markdown|md|yaml|yml)$
